Repository tbeswick96/BannerlordYetAnotherPartyOrganiser, pull requests merged in 2020-04, with the labels that each got.

#1 Improve development workflow
  Extension/GUI/PrefabExtensions/OtherTroopSortButtons.xml
  Extension/GUI/PrefabExtensions/PartyTroopSortButtons.xml
  Extension/GUI/PrefabExtensions/TroopActionButtons.xml
  Extension/Global/Strings.cs
  Extension/SubModule.xml
  Extension/YetAnotherPartyOrganiser.csproj
  README.md
  Tools/debuglink.py
  Tools/release.py
Labels: kind/tools

#6 Add basic settings
  .gitignore
  Extension/Global/Strings.cs
  Extension/PartyVmMixin.cs
  Extension/Settings.cs
  Extension/SubModule.xml
  Extension/YapoSubModule.cs
  Extension/YetAnotherPartyOrganiser.csproj
  Extension/YetAnotherPartyOrganiser.props
  README.md
Labels: kind/feature request

#9 Fixed prisoner count not updating correctly
  Extension/Services/TroopActionService.cs
Labels: kind/bug fix

#14 Implemented multipathupgrading
  Extension/Global/Strings.cs
  Extension/MultipathUpgrade/Enum/CharacterClassType.cs
  Extension/MultipathUpgrade/Enum/EquipmentProperties.cs
  Extension/MultipathUpgrade/Enum/RangedPreference.cs
  Extension/MultipathUpgrade/Model/CharacterClass.cs
  Extension/MultipathUpgrade/Model/PreferredTroopsByCulture.cs
  Extension/MultipathUpgrade/Model/UpgradeCandidate.cs
  Extension/MultipathUpgrade/MultipathUpgradeLogic.cs
  Extension/MultipathUpgrade/Services/CharacterClassCreator.cs
  Extension/MultipathUpgrade/Services/UpgradeTreeCrawler.cs
  Extension/Services/TroopActionService.cs
  Extension/Settings.cs
  Extension/YapoSubModule.cs
  Extension/YetAnotherPartyOrganiser.csproj
Labels: kind/feature

#15 Fix vanilla formation selection saving
  Extension/Fixes/Formations/FixedFormationsBehaviour.cs
  Extension/Fixes/Formations/FixedFormationsSaveableTypeDefiner.cs
  Extension/Fixes/Formations/Patches/BasicCharacterObjectPatches.cs
  Extension/Fixes/Formations/Patches/CampaignPatches.cs
  Extension/Fixes/Formations/Patches/LoadContextPatches.cs
  Extension/Global/Strings.cs
  Extension/ModuleData/FormationStrings.xml
  Extension/MultipathUpgrade/MultipathUpgradeLogic.cs
  Extension/PartyVmMixin.cs
  Extension/Settings.cs
  Extension/YapoSettings.cs
  Extension/YapoSubModule.cs
  Extension/YetAnotherPartyOrganiser.csproj
  Extension/YetAnotherPartyOrganiser.sln
  Extension/YetAnotherPartyOrganiser.sln.DotSettings
Labels: kind/feature

#22 Add total to party header troop count
  Extension/Global/Strings.cs
  Extension/ModuleData/PartyCountStrings.xml
  Extension/PartyVmMixin.cs
  Extension/Patches/PartyVmPatches.cs
  Extension/Services/PartyHeaderCountHelper.cs
  Extension/YapoSubModule.cs
  Extension/YetAnotherPartyOrganiser.csproj
  Extension/YetAnotherPartyOrganiser.sln.DotSettings
Labels: kind/feature

#31 Uiextenderlib 2.0.0
  Extension/PartyScreenExtension.cs
  Extension/PartyVmMixin.cs
  Extension/SubModule.xml
  Extension/YapoSubModule.cs
  Extension/YetAnotherPartyOrganiser.csproj
  Extension/packages.config
  README.md
Labels: kind/enhancement

#28 Feature/take upgrade cost into account
  Extension/Global/Strings.cs
  Extension/MultipathUpgrade/Model/AvailableResources.cs
  Extension/MultipathUpgrade/MultipathUpgradeLogic.cs
  Extension/PartyVmMixin.cs
  Extension/Services/RecruitmentResults.cs
  Extension/Services/TroopActionService.cs
  Extension/Services/UpgradeResults.cs
  Extension/YapoSettings.cs
  Extension/YetAnotherPartyOrganiser.csproj
  README.md
Labels: kind/feature

#36 Remove UIExtender from debug run configuration
  Extension/YetAnotherPartyOrganiser.csproj
Labels: kind/tools

#35 Implemented hold control to move entire stack
  Extension/Global/Strings.cs
  Extension/Patches/PartyCharacterVmPatches.cs
  Extension/YetAnotherPartyOrganiser.csproj
  README.md
Labels: kind/feature
